name: digitaltwin
channels:
  - conda-forge                     # third party stuff
  - defaults
dependencies:
  - python=3.9.7
  - matplotlib
  - mamba
  - scipy<1.10 # higher versions not maintained in Bayem
  - tabulate # used in bayem
  - seaborn # For nicer plots
  - doit
  - numpy
  - pandas
  - pyyaml
  - conda-ecosystem-user-package-isolation
  - pytest
  - jsonschema
  - pip
  - black
  - tectonic
  - openpyxl
  - pip:
    - "--editable=git+https://github.com/BAMresearch/bayem.git@master#egg=bayem"
    - -e .
